- name: zsh for apt distros
  apt:
    name: zsh
    state: present
  when: ansible_pkg_mgr == 'apt'
  become: yes
- name: zsh for yum distros
  yum:
    name: zsh
    state: present
  when: ansible_pkg_mgr == 'yum'
  become: yes
