#! /bin/bash

#Numix PPA
sudo apt-add-repository -y ppa:numix/ppa
#PPAs for fixed libnotify and the notifyosdconfig
sudo add-apt-repository -y ppa:leolik/leolik
sudo add-apt-repository -y ppa:nilarimogard/webupd8
#Dropbox Keyserver
sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E
#Dropbox Repository
sudo add-apt-repository -y "deb http://linux.dropbox.com/ubuntu $(lsb_release -sc) main"

sudo apt update
sudo apt -y upgrade

sudo apt install -y synapse redshift-gtk chromium-browser pepperflashplugin-nonfree synaptic unity-tweak-tool indicator-multiload keepass2 dropbox numix-icon-theme-circle compizconfig-settings-manager compiz-plugins-extra pithos clementine git cowsay xdotool ssh sshfs screenfetch mtpfs kodi steam libnotify-bin notifyosdconfig gimp

sudo apt -y autoremove

#For patched notify-osd
pkill notify-osd
