#! /bin/bash

#Numix PPA
apt-add-repository -y ppa:numix/ppa
#Dropbox Keyserver
apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E
#Dropbox Repository
add-apt-repository -y "deb http://linux.dropbox.com/ubuntu $(lsb_release -sc) main"

apt update
apt -y upgrade

apt install -y vim synapse redshift-gtk chromium-browser pepperflashplugin-nonfree synaptic unity-tweak-tool indicator-multiload keepass2 dropbox numix-icon-theme-circle compizconfig-settings-manager compiz-plugins-extra pithos clementine git cowsay xdotool ssh sshfs screenfetch mtpfs kodi steam libnotify-bin notifyosdconfig gimp

apt -y autoremove
