---
- hosts: localhost
  vars:
    - stowLocation: $HOME/installscripts/configs
  tasks:
    - name: neovim autoload directory
      file:
        path: "{{ lookup('env','HOME') }}/.local/share/nvim/site/autoload"
        state: directory
    - name: vim-plug plugin manager
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.local/share/nvim/site/autoload/plug.vim
    - name: set neovim config
      command:
        stow -d {{ stowLocation }} -t $HOME neovim
    - name: install neovim plugins
      command:
        nvim +PlugInstall +UpdateRemotePlugins +qall
