- name: neovim autoload directory
  file:
    path: "{{ lookup('env','HOME') }}/.local/share/nvim/site/autoload"
    state: directory
- name: vim-plug plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim
- name: neovim config directory
  file:
    path: "{{ lookup('env','HOME') }}/.config/nvim"
    state: directory
- name: install neovim plugins
  command:
    cmd: nvim +PlugInstall +UpdateRemotePlugins +qall
    creates: "{{ lookup('env','HOME') }}/.config/nvim/plugged" 
