- name: neovim autoload directory
  file:
    path: "{{ lookup('env','HOME') }}/.local/share/nvim/site/autoload"
    state: directory
- name: vim-plug plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim
- name: neovim config directory
  file:
    path: "{{ lookup('env','HOME') }}/.config/nvim"
    state: directory
- name: set neovim config
  file:
    src: "{{ neovim_config | realpath }}"
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim/init.vim"
    state: link
- name: install neovim plugins
  command:
    nvim +PlugInstall +UpdateRemotePlugins +qall
- name: alias vi to nvim
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/.bash_aliases"
    line: alias vi='nvim'
    create: yes
