---
- hosts: localhost
  tasks:
    - name: i3 ppa
      # right-click in fullscreen might freeze Xorg with Ubuntu's old package
      apt_repository:
        repo: 'ppa:verterok/i3'
    - name: i3 installed
      apt:
        name: i3
      become: yes
