---
- name: find files
  find:
    # path: "{{ stow_location }}"
    path: "{{ stow_location | realpath }}/{{ package }}"
    recurse: yes
    file_type: file
    hidden: yes
  register: files
- name: link
  file:
    src: "{{ item.path }}"
    dest: "{{ target_dir }}/{{ item.path | relpath(package_path) }}"
    state: link
  with_items: "{{ files.files }}"
