---
- hosts: localhost
  tasks:
    - package:
        name: emacs
      become: true
    - git:
        repo: https://github.com/doomemacs/doomemacs
        dest: ~/.emacs.d
        depth: 1
        force: true
    - include_role:
        name: stow
      vars:
        package: emacs
    - shell:
        cmd: ~/.emacs.d/bin/doom install
        creates: ~/.doom.d/init.el

