---
- hosts: localhost
  tasks:
    - name: install common CLI packages
      package:
        name:
          - tmux
          - neovim
          - trash-cli
          - zsh
          - git
          - freeipa-client
          - highlight
          - fd-find
          - ripgrep
          - units
          - fzf
          - nmap
      become: yes

    - name: install common GUI packages
      package:
        name:
          - keepassxc
          - seafile-client
      become: yes
