---
- hosts: all
  tasks:
    - name: install common CLI packages
      package:
        name:
          - tmux
          - neovim
          - trash-cli
          - zsh
          - git
          - freeipa-client
          - highlight
      become: yes
