---
- hosts: localhost
  become_user: root
  become: yes
  tasks:
    - name: upgraded software
      apt:
        update_cache: yes
        upgrade: dist
    - block:
      - name: neovim ppa
        apt_repository:
          repo: 'ppa:neovim-ppa/stable'
      - name: neovim package
        apt:
          name:
            - neovim
    - block:
      - name: seafile ppa
        apt_repository:
          repo: 'ppa:seafile/seafile-client'
      - name: seafile package
        apt:
          name: seafile-gui
    - block:
      - name: neofetch ppa
        apt_repository:
          repo: 'ppa:dawidd0811/neofetch-daily'
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version <= '16.10'
      - name: neofetch package
        apt: 
          name:
            - neofetch
    - name: geary ppa
      apt_repository:
        repo: 'ppa:geary-team/releases'
    - name: geary installed
      apt:
        name: geary
    - name: kodi ppa
      apt_repository:
        repo: 'ppa:team-xbmc/ppa'
    - name: custom system packages
      apt:
        name:
          - vim
          - git
          - stow
          - zsh
          - ncdu
          - ranger
          - htop
          - iotop
          - nmap
    - name: user packages
      apt:
        name:
          - keepass2
          - redshift-gtk
          - chromium-browser
          - qbittorrent
          - libreoffice
          - pandoc
          - pandoc-citeproc
          - texlive-xetex
          - pepperflashplugin-nonfree
          - rofi
          - scrot
    - name: media packages
      apt:
        name:
          - pithos
          - clementine
          - kodi
          - beets
